apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: wesleywillians/test-gitops
  newName: wesleywillians/test-gitops
  newTag: abca
