apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: hello-gitops
images:
- name: nginx
  newName: wesleywillians/nginx
  newTag: bd0b95a1e7e31fd3a30c0a979ffbfc45761b001f
