apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: goapp
  newName: wesleywillians/test-gitops
  newTag: 6b15ba7b23af65f85a794c89246d6d482face870
- name: wesleywillians/test-gitops
  newName: wesleywillians/test-gitops
  newTag: abca
